language: rust
sudo: false

# Ref: https://rust-lang.github.io/mdBook/continuous-integration.html

# Cache mdbook install, etc. for fast builds
cache:
  - cargo

rust:
  - stable

# Make sure we have mdbook
#   test -x <file>: <file> exists and we can execute it.
before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
  - cargo install-update -a

script:
  - mdbook build && mdbook test

# Deploy to pages.
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book
  keep-history: false
  on:
    branch: main
