[book]
authors = ["Math 334 - Au 2021"]
language = "en"
multilingual = false
src = "src"
title = "Math 334 Lecture Notes"

[output.html]
mathjax-support = true
curly-quotes = true

[output.html.playground]
editable = true

